### PR TITLE
Fix @import not working

### PR DESCRIPTION
**Pull request by mlaxwong**
Fix @import not working

### CODE REVIEW

**Comment by LucidTaZ** [comment]
Thank you kindly. I will work on making the tests more resilient (it complains that it didn't expect the call) and also a test for the import feature should be added.

**Comment by mlaxwong** [comment]
Thanks @LucidTaZ ,  I like your converter library.

**Comment by LucidTaZ** [comment]
I will merge this now and fix the tests in a separate commit, so we don't have to hassle over repository access rights.

Thanks again!

**Comment by mlaxwong** [comment]
Your welcome, thanks too!

**Pull request merged**
